### PR TITLE
Add IPFS nodes

### PR DESCRIPTION
**Pull request by confleux**

### CODE REVIEW

**Comment by confleux** [comment]
First need to merge #69, so that I update this PR to match new services structure

**Review by RealGoodProgrammer — APPROVED** [review]

**Comment by bludnic** [comment]
Merge #69. Do you still need to make changes to this PR? @confleux

**Comment by bludnic** [comment]
@confleux I suggest to slightly change the structure to this:

```json5
"services": {
  "infoService": {
     "description": [],
     "list": [],
     "healthCheck": {}
  },
  "ipfsNode": {
     "description": [],
     "list": [],
     "healthCheck": {}
  }
}
```

Please ensure that other services added before also follow that structure. Also don't forget to update the Swagger schema. You can validate it here https://editor.swagger.io/

**Comment by bludnic** [comment]
- Reused the type `NodeInfo` for services https://github.com/Adamant-im/adamant-wallets/pull/87/commits/f0f2a66356201c68e9f73a7b52cfe1a796048a85
- Fixed the type of services property from `Service` to `Record<string, Service>` https://github.com/Adamant-im/adamant-wallets/pull/87/commits/9c30a9631e9e1855ee149913c68cb2db503b031e

**Pull request merged**
