### PR TITLE
feat(adamant): add custom WebSocket port for specific nodes

### PR DESCRIPTION
**Pull request by bludnic**
Added new param `wsPort` in the ADAMANT nodes configuration.

If the `wsPort` is not specified then, depending on the `nodes[].url` protocol:

- If `http`, then `36668` will be used as a default port
- If `https`, then `443` will be used as a default port

### Checklist

- [x] Add custom WS ports for `https://node1.adamant.business` and `http://184.94.215.92`
- [x] Add examples with `wsPort` in README.md
- [ ] Update swagger schema

### CODE REVIEW

**Comment by bludnic** [comment]
[Use more nodes (config files): Make sure app uses new ports](https://trello.com/c/gzKXFMtY/377-use-more-nodes-config-files-make-sure-app-uses-new-ports)

**Review by adamant-al — CHANGES_REQUESTED** [review]
Is it reasonable to add `wsPort` to the config, if `/node/api/status` returns the `wsPort` for a node?

Does an app start a socked connection ahead of `/node/api/status` REST request?

Is there a use case, when REST is disabled, and socket is enabled?

**Comment by bludnic** [comment]
> Is it reasonable to add wsPort to the config, if /node/api/status returns the wsPort for a node?

The current implementation of the PWA is based on a static configuration. The ports are harcoded in a JSON file, and the socket port from `GET /node/api/status` is ignored.

We can either:

1. Move harcoded `wsPort` to the `adamant-wallets` repository
2. Or, rewrite the PWA codebase, so that the `wsPort` is be obtained from `GET /node/api/status`

I think we need to ask the iOS devs, and depending on their current implementation we can choose the solution.

**Comment by bludnic** [comment]
I checked the api client in the PWA. Looks like the app already uses the `wsPort` from `GET /node/api/status`.

```js
      return this.request({ url: '/api/node/status' })
        .then(res => {
          if (res.success) {
            return {
              online: true,
              version: res.version.version,
              height: Number(res.network.height),
              ping: Date.now() - time,
              socketSupport: res.wsClient && res.wsClient.enabled,
              wsPort: res.wsClient ? res.wsClient.port : false
            }
          }
          throw new Error('Request to /api/node/status was unsuccessful')
        })
```

I guess this PR is no longer relevant.

**Comment by adamant-al** [comment]
@just-software-dev @StanislavDevIOS

**Comment by just-software-dev** [comment]
If the PR is not relevant, let's reject it. We don't need information duplication

**Review by just-software-dev — CHANGES_REQUESTED** [review]
If the PR is not relevant, let's reject it. We don't need information duplication. On iOS we get info about wsPort from status.

**Comment by adamant-al** [comment]
@bludnic Close the PR.

**Pull request closed without merging**
