### PR TITLE
Add ADM nodes

### PR DESCRIPTION
**Pull request by confleux**
Proxy to ADM nodes

### CODE REVIEW

**Comment by adamant-al** [comment]
@confleux 
@bludnic 

Add domain links to enable PWA.
E.g., http://ec2-54-197-36-175.compute-1.amazonaws.com:36666

Is `*.amazonaws.com` enough or better prepare other domain?

**Comment by adamant-al** [comment]
@confleux 
It seems PWA requires https.

**Comment by confleux** [comment]
> @confleux 
> 
> It seems PWA requires https.

That domain doesn't support https curently. Can it be set to work with https? @bludnic

**Comment by bludnic** [comment]
@confleux since the browsers are blocking the requests to HTTP originated from HTTPS, it will not work, so for PWA we have two options:

- Serve adm.im domain also under HTTP
- Add HTTPS support for the new nodes

Android and Desktop apps will work fine with HTTP.

**Comment by confleux** [comment]
> @confleux since browsers are blocking the requests to HTTP originated from HTTPS, it will not work, so for PWA we have two options:
> 
> * Serve adm.im domain also under HTTP
> * Add HTTPS support for the new nodes
> 
> Android and Desktop apps will work fine with HTTP.

I think there is no need for HTTPS. Anyway, PWA cannot be open without VPN, while apps can. Thus, if user can access PWA, it doesn't need any proxy nodes, as current will work.

**Review by bludnic — APPROVED** [review]

**Comment by bludnic** [comment]
Can it be merged? @confleux

**Review by adamant-al — APPROVED** [review]

**Comment by adamant-al** [comment]
@just-software-dev 
@yoxira 
Review.

**Review by yoxira — APPROVED** [review]

**Comment by adamant-al** [comment]
@confleux 
Merge

**Pull request merged**
