### PR TITLE
Implemented icons for new wallets

### PR DESCRIPTION
**Pull request by StanislavDevIOS**
Implemented icons for new wallets

### CODE REVIEW

**Review by adamant-al — APPROVED** [review]

**Comment by martiliones** [comment]
1. fix spaces
2. add new lines at the end of the files
3. can we make all the icons in one style? e.g. all coin logos inside a circle

<p float="left">
  
   
  
</p>

**Comment by adamant-al** [comment]
> 1. fix spaces
> 2. add new lines at the end of the files
> 3. can we make all the icons in one style? e.g. all coin logos inside a circle

For 3, we'll see yet how it will look like. Currently all icons in the app have no circles.

**Review by bludnic — CHANGES_REQUESTED** [review]
Is there a reason why the `Images` dir starts with a capital letter? Can we rename it to `images`?

**Comment by bludnic** [comment]
It may be a reasonable to generate icons with a CLI tool like [cordova-res](https://www.npmjs.com/package/cordova-res).   The Vue icon-component can be generated using `mustache` template + a tiny node script. In this case we need to store only one icon in the repo. What do you think?

**Comment by adamant-al** [comment]
> Is there a reason why the `Images` dir starts with a capital letter? Can we rename it to `images`?

Please propose these changes.
Also update Readme.
@StanislavDevIOS Make sure we read `images` instead of `Images`.

**Comment by adamant-al** [comment]
> It may be a reasonable to generate icons with a CLI tool like [cordova-res](https://www.npmjs.com/package/cordova-res). The Vue icon-component can be generated using `mustache` template + a tiny node script. In this case we need to store only one icon in the repo. What do you think?

For me it's convenient to have 2 files for svg, as I can download and re-use them not only for PWA.
As for png, I see it's important to create them with no efforts. If Artem is comfortable with `cordova-res`, so it's good.
@artysparrow What do you think about this?

**Comment by artysparrow** [comment]
1. I think icons should be standardized to a uniform format for a better UI as shown in the attachment.
2. If it's more convenient for you to work through the CLI tool for icons generation, no problem.

pwa_wallet

ios_wallet

**Review by artysparrow — APPROVED** [review]

**Comment by adamant-al** [comment]
I don't want standardized icons for circled / not circled. Please leave current icons as is, and we'll see on device for new ones. So every icon can be unique in its appearance.

Screenshot 2023-01-02 в 20 11 18

image

**Comment by adamant-al** [comment]
> 1. fix spaces
> 2. add new lines at the end of the files

Propose changes for these two.

**Comment by martiliones** [comment]
I really love ADAMANT logo in blue circle. How about making all logos without the circle, but adding them for active ones?

image

**Comment by adamant-al** [comment]
> I really love ADAMANT logo in blue circle. How about making all logos without the circle, but adding them for active ones? Each logo can have a unique circle color as well

For PWA, let's see how it will look live. I have bad imagination and prefer to try.

**Pull request merged**
